### ISSUE TITLE
"dispenserEquipping" option drastically breaks dispenser behaviour

### ISSUE THREAD

**Issue by kikugie** [WerDei/Server-Hats#1]
If items are allowed to be hats following properties break (In each case item just drops instead)
- Minecarts don't dispense on rails
- Arrow in front of armor stand doesnt shoot (equips as a hat)
- Doesn't place/take liquid with a bucket
- Boats don't dispense on water
- Sheep are not sheared
- Flint and steel doensn't place fire
- Every dispensable projectile doesn't shoot (arrows, fire charges, fireworks, splash potions, xp bottles, etc)
- Spawn eggs don't spawn mobs
- Bone meal doesn't work
Might (likely) there're more, I checked most, but not every dispenser behavior
What **doesn't** break:
- Placing carved pumpkin on iron/snow golem base and summoning it
- Placing wither skeleton skulls on a wither base

![2021-12-10_01 14 17](https://user-images.githubusercontent.com/50152507/145491155-47ee40f5-3287-4282-b6b7-0f033e021a48.png)

**Comment by WerDei** [comment]
That's a pretty obvious oversight by me, I'm sorry for that. Thankfully, the fix was pretty simple. Thank you for the report!

**Comment by AZMindroma** [comment]
Hello, I'm typing here because the same issues occur on the newest version 0.13 (for 1.19.3). While me and my friend haven't tested this on other behavior, the sheep shearing is broken.

**Comment by WerDei** [comment]
Yep, did an oopsie when rewriting dispenser behaviour for hats. Should be fixed now, will publish the update shortly.
