### ISSUE TITLE
Crashes upon world loading on 1.19

### ISSUE THREAD

**Issue by showercurtain** [WerDei/Server-Hats#3]
When creating a world or loading an existing one on 1.19, the game crashes.
Crash report: https://crashy.net/D8UhlJAAe4Ed2m901IWr

**Comment by WerDei** [comment]
With 1.19 Mojang changed how tags work again, and I didn't have time to look into that yet. But it's on my radar, and I will update the mod when I can

**Comment by ghost** [comment]
Hello, sounds great - thanks already 🥰

**Comment by WerDei** [comment]
Update is out. For the time being, there are no item/item tag suggestions when using the /hats command, but everything else _should_ work normally (including on 1.19.1). Thank you for waiting!
