### ISSUE TITLE
Cannot equip allowed items into an Armor Stand's hand

### ISSUE THREAD

**Issue by onycius** [WerDei/Server-Hats#4]
Right-clicking an item onto an armorstand will prioritize the helmet slot, no matter what type of item it is.

ex) right clicking a dirt block on the armor stand will give it a dirt block head

This is fine and all but the real problem comes up when i also want to equip other items, such as swords.
The sword will also override the helmet slot.

**Comment by WerDei** [comment]
I could only reproduce the issue with items that normally can only be put into armorstand's hand - I'm assuming that's what you meant.

Fixed it by adding custom logic - if you look at armorstand's head, item will be put in the head slot; when looking anywhere else it will be put into its hand instead (If an armor stand has arms, of course).

Will publish to Curse/Modrinth shortly
