### ISSUE TITLE
Bug: using this mod, you can enchant your armor and tools at Aqua Affinity and Respiration

### ISSUE THREAD

**Issue by Vi-Tul** [WerDei/Server-Hats#5]
![2022-08-31_15 55 49](https://user-images.githubusercontent.com/92220631/187663172-26148bfd-e898-4303-a752-e7f7e8e80f63.png)
![2022-08-31_15 55 53](https://user-images.githubusercontent.com/92220631/187663182-079f6079-4acb-4d96-8d06-0cd92b6d3b2b.png)

Also, villagers can give you items with these enchantments 
![2022-08-31_15 50 11](https://user-images.githubusercontent.com/92220631/187662254-eb4de2cc-e253-41c1-8145-696a9fdb8aad.png)

**Comment by Skeithh** [comment]
Are you sure it's this mod? I've got the same issue on my game but removing the mod didn't fix it.

**Comment by WerDei** [comment]
> Are you sure it's this mod? I've got the same issue on my game but removing the mod didn't fix it.

Removing it shouldn't fix the already enchanted tools\unlocked trades (the game has already saved them at that point), but it should prevent new ones from appearing. But If you still get these encheantments on new trades then yes, it's (very likely) because of another mod.

**Comment by Vi-Tul** [comment]
> 



> Removing it shouldn't fix the already enchanted tools\unlocked trades (the game has already saved them at that point), but it should prevent new ones from appearing.

Yeah, after removing this mod everything returned to normal.

**Comment by WerDei** [comment]
Couldn't think of a clean way of fixing this, so I just removed the ability to enchant hat items with helmet enchantments. Update is up on Modrinth, and is under review on Curse. Sorry for taking so long!

**Comment by Vi-Tul** [comment]
I think this is the most logical way of fixing this issue :)
