### ISSUE TITLE
1.19.3?

### ISSUE THREAD

**Issue by Vi-Tul** [WerDei/Server-Hats#6]
Is the project alive?

**Comment by WerDei** [comment]
I'm hoping I can update the mod over the coming week or two, but no promises.

**Comment by WerDei** [comment]
Sike, looked into it today and it turned out much less work than I expected. 
Meanwhile I rewrote the code a bit to hopefully create less bugs in the future. I'm sure this sentence will age well.

Update is up on Modrinth and is under review on Curse. Thanks for waiting!

**Comment by Vi-Tul** [comment]
Yay!
